//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SchoolManagement.Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="schollSoap", Namespace="http://tempuri.org/")]
    public partial class scholl : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback attentab_insertOperationCompleted;
        
        private System.Threading.SendOrPostCallback attentab_updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback attentab_deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback entab_insertOperationCompleted;
        
        private System.Threading.SendOrPostCallback entab_updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback entab_deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Sectiontab_insertOperationCompleted;
        
        private System.Threading.SendOrPostCallback Sectiontab_updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Sectiontab_deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback tabdaftar_insertOperationCompleted;
        
        private System.Threading.SendOrPostCallback tabdaftar_updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback tabdaftar_deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback tabguru_insertOperationCompleted;
        
        private System.Threading.SendOrPostCallback tabguru_updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback tabguru_deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback tabkehadiran_insertOperationCompleted;
        
        private System.Threading.SendOrPostCallback tabkehadiran_updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback tabkehadiran_deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback tabsiswa_insertOperationCompleted;
        
        private System.Threading.SendOrPostCallback tabsiswa_updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback tabsiswa_deleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public scholl() {
            this.Url = global::SchoolManagement.Properties.Settings.Default.SchoolManagement_Service_scholl;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event attentab_insertCompletedEventHandler attentab_insertCompleted;
        
        /// <remarks/>
        public event attentab_updateCompletedEventHandler attentab_updateCompleted;
        
        /// <remarks/>
        public event attentab_deleteCompletedEventHandler attentab_deleteCompleted;
        
        /// <remarks/>
        public event entab_insertCompletedEventHandler entab_insertCompleted;
        
        /// <remarks/>
        public event entab_updateCompletedEventHandler entab_updateCompleted;
        
        /// <remarks/>
        public event entab_deleteCompletedEventHandler entab_deleteCompleted;
        
        /// <remarks/>
        public event Sectiontab_insertCompletedEventHandler Sectiontab_insertCompleted;
        
        /// <remarks/>
        public event Sectiontab_updateCompletedEventHandler Sectiontab_updateCompleted;
        
        /// <remarks/>
        public event Sectiontab_deleteCompletedEventHandler Sectiontab_deleteCompleted;
        
        /// <remarks/>
        public event tabdaftar_insertCompletedEventHandler tabdaftar_insertCompleted;
        
        /// <remarks/>
        public event tabdaftar_updateCompletedEventHandler tabdaftar_updateCompleted;
        
        /// <remarks/>
        public event tabdaftar_deleteCompletedEventHandler tabdaftar_deleteCompleted;
        
        /// <remarks/>
        public event tabguru_insertCompletedEventHandler tabguru_insertCompleted;
        
        /// <remarks/>
        public event tabguru_updateCompletedEventHandler tabguru_updateCompleted;
        
        /// <remarks/>
        public event tabguru_deleteCompletedEventHandler tabguru_deleteCompleted;
        
        /// <remarks/>
        public event tabkehadiran_insertCompletedEventHandler tabkehadiran_insertCompleted;
        
        /// <remarks/>
        public event tabkehadiran_updateCompletedEventHandler tabkehadiran_updateCompleted;
        
        /// <remarks/>
        public event tabkehadiran_deleteCompletedEventHandler tabkehadiran_deleteCompleted;
        
        /// <remarks/>
        public event tabsiswa_insertCompletedEventHandler tabsiswa_insertCompleted;
        
        /// <remarks/>
        public event tabsiswa_updateCompletedEventHandler tabsiswa_updateCompleted;
        
        /// <remarks/>
        public event tabsiswa_deleteCompletedEventHandler tabsiswa_deleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/attentab_insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string attentab_insert(int id, string namaSiswa, string status) {
            object[] results = this.Invoke("attentab_insert", new object[] {
                        id,
                        namaSiswa,
                        status});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void attentab_insertAsync(int id, string namaSiswa, string status) {
            this.attentab_insertAsync(id, namaSiswa, status, null);
        }
        
        /// <remarks/>
        public void attentab_insertAsync(int id, string namaSiswa, string status, object userState) {
            if ((this.attentab_insertOperationCompleted == null)) {
                this.attentab_insertOperationCompleted = new System.Threading.SendOrPostCallback(this.Onattentab_insertOperationCompleted);
            }
            this.InvokeAsync("attentab_insert", new object[] {
                        id,
                        namaSiswa,
                        status}, this.attentab_insertOperationCompleted, userState);
        }
        
        private void Onattentab_insertOperationCompleted(object arg) {
            if ((this.attentab_insertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.attentab_insertCompleted(this, new attentab_insertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/attentab_update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string attentab_update(int id, string namaSiswa, string status) {
            object[] results = this.Invoke("attentab_update", new object[] {
                        id,
                        namaSiswa,
                        status});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void attentab_updateAsync(int id, string namaSiswa, string status) {
            this.attentab_updateAsync(id, namaSiswa, status, null);
        }
        
        /// <remarks/>
        public void attentab_updateAsync(int id, string namaSiswa, string status, object userState) {
            if ((this.attentab_updateOperationCompleted == null)) {
                this.attentab_updateOperationCompleted = new System.Threading.SendOrPostCallback(this.Onattentab_updateOperationCompleted);
            }
            this.InvokeAsync("attentab_update", new object[] {
                        id,
                        namaSiswa,
                        status}, this.attentab_updateOperationCompleted, userState);
        }
        
        private void Onattentab_updateOperationCompleted(object arg) {
            if ((this.attentab_updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.attentab_updateCompleted(this, new attentab_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/attentab_delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string attentab_delete(int id) {
            object[] results = this.Invoke("attentab_delete", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void attentab_deleteAsync(int id) {
            this.attentab_deleteAsync(id, null);
        }
        
        /// <remarks/>
        public void attentab_deleteAsync(int id, object userState) {
            if ((this.attentab_deleteOperationCompleted == null)) {
                this.attentab_deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.Onattentab_deleteOperationCompleted);
            }
            this.InvokeAsync("attentab_delete", new object[] {
                        id}, this.attentab_deleteOperationCompleted, userState);
        }
        
        private void Onattentab_deleteOperationCompleted(object arg) {
            if ((this.attentab_deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.attentab_deleteCompleted(this, new attentab_deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/entab_insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string entab_insert(int id, string studentName, string section, System.DateTime enrollDate) {
            object[] results = this.Invoke("entab_insert", new object[] {
                        id,
                        studentName,
                        section,
                        enrollDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void entab_insertAsync(int id, string studentName, string section, System.DateTime enrollDate) {
            this.entab_insertAsync(id, studentName, section, enrollDate, null);
        }
        
        /// <remarks/>
        public void entab_insertAsync(int id, string studentName, string section, System.DateTime enrollDate, object userState) {
            if ((this.entab_insertOperationCompleted == null)) {
                this.entab_insertOperationCompleted = new System.Threading.SendOrPostCallback(this.Onentab_insertOperationCompleted);
            }
            this.InvokeAsync("entab_insert", new object[] {
                        id,
                        studentName,
                        section,
                        enrollDate}, this.entab_insertOperationCompleted, userState);
        }
        
        private void Onentab_insertOperationCompleted(object arg) {
            if ((this.entab_insertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.entab_insertCompleted(this, new entab_insertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/entab_update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string entab_update(int id, string studentName, string section, System.DateTime enrollDate) {
            object[] results = this.Invoke("entab_update", new object[] {
                        id,
                        studentName,
                        section,
                        enrollDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void entab_updateAsync(int id, string studentName, string section, System.DateTime enrollDate) {
            this.entab_updateAsync(id, studentName, section, enrollDate, null);
        }
        
        /// <remarks/>
        public void entab_updateAsync(int id, string studentName, string section, System.DateTime enrollDate, object userState) {
            if ((this.entab_updateOperationCompleted == null)) {
                this.entab_updateOperationCompleted = new System.Threading.SendOrPostCallback(this.Onentab_updateOperationCompleted);
            }
            this.InvokeAsync("entab_update", new object[] {
                        id,
                        studentName,
                        section,
                        enrollDate}, this.entab_updateOperationCompleted, userState);
        }
        
        private void Onentab_updateOperationCompleted(object arg) {
            if ((this.entab_updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.entab_updateCompleted(this, new entab_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/entab_delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string entab_delete(int id) {
            object[] results = this.Invoke("entab_delete", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void entab_deleteAsync(int id) {
            this.entab_deleteAsync(id, null);
        }
        
        /// <remarks/>
        public void entab_deleteAsync(int id, object userState) {
            if ((this.entab_deleteOperationCompleted == null)) {
                this.entab_deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.Onentab_deleteOperationCompleted);
            }
            this.InvokeAsync("entab_delete", new object[] {
                        id}, this.entab_deleteOperationCompleted, userState);
        }
        
        private void Onentab_deleteOperationCompleted(object arg) {
            if ((this.entab_deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.entab_deleteCompleted(this, new entab_deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Sectiontab_insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Sectiontab_insert(int sectionId, string studentName, string section) {
            object[] results = this.Invoke("Sectiontab_insert", new object[] {
                        sectionId,
                        studentName,
                        section});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Sectiontab_insertAsync(int sectionId, string studentName, string section) {
            this.Sectiontab_insertAsync(sectionId, studentName, section, null);
        }
        
        /// <remarks/>
        public void Sectiontab_insertAsync(int sectionId, string studentName, string section, object userState) {
            if ((this.Sectiontab_insertOperationCompleted == null)) {
                this.Sectiontab_insertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSectiontab_insertOperationCompleted);
            }
            this.InvokeAsync("Sectiontab_insert", new object[] {
                        sectionId,
                        studentName,
                        section}, this.Sectiontab_insertOperationCompleted, userState);
        }
        
        private void OnSectiontab_insertOperationCompleted(object arg) {
            if ((this.Sectiontab_insertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Sectiontab_insertCompleted(this, new Sectiontab_insertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Sectiontab_update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Sectiontab_update(int sectionId, string studentName, string section) {
            object[] results = this.Invoke("Sectiontab_update", new object[] {
                        sectionId,
                        studentName,
                        section});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Sectiontab_updateAsync(int sectionId, string studentName, string section) {
            this.Sectiontab_updateAsync(sectionId, studentName, section, null);
        }
        
        /// <remarks/>
        public void Sectiontab_updateAsync(int sectionId, string studentName, string section, object userState) {
            if ((this.Sectiontab_updateOperationCompleted == null)) {
                this.Sectiontab_updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSectiontab_updateOperationCompleted);
            }
            this.InvokeAsync("Sectiontab_update", new object[] {
                        sectionId,
                        studentName,
                        section}, this.Sectiontab_updateOperationCompleted, userState);
        }
        
        private void OnSectiontab_updateOperationCompleted(object arg) {
            if ((this.Sectiontab_updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Sectiontab_updateCompleted(this, new Sectiontab_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Sectiontab_delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Sectiontab_delete(int sectionId) {
            object[] results = this.Invoke("Sectiontab_delete", new object[] {
                        sectionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Sectiontab_deleteAsync(int sectionId) {
            this.Sectiontab_deleteAsync(sectionId, null);
        }
        
        /// <remarks/>
        public void Sectiontab_deleteAsync(int sectionId, object userState) {
            if ((this.Sectiontab_deleteOperationCompleted == null)) {
                this.Sectiontab_deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSectiontab_deleteOperationCompleted);
            }
            this.InvokeAsync("Sectiontab_delete", new object[] {
                        sectionId}, this.Sectiontab_deleteOperationCompleted, userState);
        }
        
        private void OnSectiontab_deleteOperationCompleted(object arg) {
            if ((this.Sectiontab_deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Sectiontab_deleteCompleted(this, new Sectiontab_deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/tabdaftar_insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string tabdaftar_insert(int nis, string namaSiswa, double rataRataNilai, System.DateTime tanggalPendaftaran) {
            object[] results = this.Invoke("tabdaftar_insert", new object[] {
                        nis,
                        namaSiswa,
                        rataRataNilai,
                        tanggalPendaftaran});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tabdaftar_insertAsync(int nis, string namaSiswa, double rataRataNilai, System.DateTime tanggalPendaftaran) {
            this.tabdaftar_insertAsync(nis, namaSiswa, rataRataNilai, tanggalPendaftaran, null);
        }
        
        /// <remarks/>
        public void tabdaftar_insertAsync(int nis, string namaSiswa, double rataRataNilai, System.DateTime tanggalPendaftaran, object userState) {
            if ((this.tabdaftar_insertOperationCompleted == null)) {
                this.tabdaftar_insertOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontabdaftar_insertOperationCompleted);
            }
            this.InvokeAsync("tabdaftar_insert", new object[] {
                        nis,
                        namaSiswa,
                        rataRataNilai,
                        tanggalPendaftaran}, this.tabdaftar_insertOperationCompleted, userState);
        }
        
        private void Ontabdaftar_insertOperationCompleted(object arg) {
            if ((this.tabdaftar_insertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tabdaftar_insertCompleted(this, new tabdaftar_insertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/tabdaftar_update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string tabdaftar_update(int nis, string namaSiswa, double rataRataNilai, System.DateTime tanggalPendaftaran) {
            object[] results = this.Invoke("tabdaftar_update", new object[] {
                        nis,
                        namaSiswa,
                        rataRataNilai,
                        tanggalPendaftaran});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tabdaftar_updateAsync(int nis, string namaSiswa, double rataRataNilai, System.DateTime tanggalPendaftaran) {
            this.tabdaftar_updateAsync(nis, namaSiswa, rataRataNilai, tanggalPendaftaran, null);
        }
        
        /// <remarks/>
        public void tabdaftar_updateAsync(int nis, string namaSiswa, double rataRataNilai, System.DateTime tanggalPendaftaran, object userState) {
            if ((this.tabdaftar_updateOperationCompleted == null)) {
                this.tabdaftar_updateOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontabdaftar_updateOperationCompleted);
            }
            this.InvokeAsync("tabdaftar_update", new object[] {
                        nis,
                        namaSiswa,
                        rataRataNilai,
                        tanggalPendaftaran}, this.tabdaftar_updateOperationCompleted, userState);
        }
        
        private void Ontabdaftar_updateOperationCompleted(object arg) {
            if ((this.tabdaftar_updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tabdaftar_updateCompleted(this, new tabdaftar_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/tabdaftar_delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string tabdaftar_delete(int nis) {
            object[] results = this.Invoke("tabdaftar_delete", new object[] {
                        nis});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tabdaftar_deleteAsync(int nis) {
            this.tabdaftar_deleteAsync(nis, null);
        }
        
        /// <remarks/>
        public void tabdaftar_deleteAsync(int nis, object userState) {
            if ((this.tabdaftar_deleteOperationCompleted == null)) {
                this.tabdaftar_deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontabdaftar_deleteOperationCompleted);
            }
            this.InvokeAsync("tabdaftar_delete", new object[] {
                        nis}, this.tabdaftar_deleteOperationCompleted, userState);
        }
        
        private void Ontabdaftar_deleteOperationCompleted(object arg) {
            if ((this.tabdaftar_deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tabdaftar_deleteCompleted(this, new tabdaftar_deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/tabguru_insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string tabguru_insert(int idGuru, string namaGuru, string jenisKelamin, string nomorHp) {
            object[] results = this.Invoke("tabguru_insert", new object[] {
                        idGuru,
                        namaGuru,
                        jenisKelamin,
                        nomorHp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tabguru_insertAsync(int idGuru, string namaGuru, string jenisKelamin, string nomorHp) {
            this.tabguru_insertAsync(idGuru, namaGuru, jenisKelamin, nomorHp, null);
        }
        
        /// <remarks/>
        public void tabguru_insertAsync(int idGuru, string namaGuru, string jenisKelamin, string nomorHp, object userState) {
            if ((this.tabguru_insertOperationCompleted == null)) {
                this.tabguru_insertOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontabguru_insertOperationCompleted);
            }
            this.InvokeAsync("tabguru_insert", new object[] {
                        idGuru,
                        namaGuru,
                        jenisKelamin,
                        nomorHp}, this.tabguru_insertOperationCompleted, userState);
        }
        
        private void Ontabguru_insertOperationCompleted(object arg) {
            if ((this.tabguru_insertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tabguru_insertCompleted(this, new tabguru_insertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/tabguru_update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string tabguru_update(int idGuru, string namaGuru, string jenisKelamin, string nomorHp) {
            object[] results = this.Invoke("tabguru_update", new object[] {
                        idGuru,
                        namaGuru,
                        jenisKelamin,
                        nomorHp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tabguru_updateAsync(int idGuru, string namaGuru, string jenisKelamin, string nomorHp) {
            this.tabguru_updateAsync(idGuru, namaGuru, jenisKelamin, nomorHp, null);
        }
        
        /// <remarks/>
        public void tabguru_updateAsync(int idGuru, string namaGuru, string jenisKelamin, string nomorHp, object userState) {
            if ((this.tabguru_updateOperationCompleted == null)) {
                this.tabguru_updateOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontabguru_updateOperationCompleted);
            }
            this.InvokeAsync("tabguru_update", new object[] {
                        idGuru,
                        namaGuru,
                        jenisKelamin,
                        nomorHp}, this.tabguru_updateOperationCompleted, userState);
        }
        
        private void Ontabguru_updateOperationCompleted(object arg) {
            if ((this.tabguru_updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tabguru_updateCompleted(this, new tabguru_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/tabguru_delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string tabguru_delete(int idGuru) {
            object[] results = this.Invoke("tabguru_delete", new object[] {
                        idGuru});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tabguru_deleteAsync(int idGuru) {
            this.tabguru_deleteAsync(idGuru, null);
        }
        
        /// <remarks/>
        public void tabguru_deleteAsync(int idGuru, object userState) {
            if ((this.tabguru_deleteOperationCompleted == null)) {
                this.tabguru_deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontabguru_deleteOperationCompleted);
            }
            this.InvokeAsync("tabguru_delete", new object[] {
                        idGuru}, this.tabguru_deleteOperationCompleted, userState);
        }
        
        private void Ontabguru_deleteOperationCompleted(object arg) {
            if ((this.tabguru_deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tabguru_deleteCompleted(this, new tabguru_deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/tabkehadiran_insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string tabkehadiran_insert(int nis, string namaSiswa, string presensi) {
            object[] results = this.Invoke("tabkehadiran_insert", new object[] {
                        nis,
                        namaSiswa,
                        presensi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tabkehadiran_insertAsync(int nis, string namaSiswa, string presensi) {
            this.tabkehadiran_insertAsync(nis, namaSiswa, presensi, null);
        }
        
        /// <remarks/>
        public void tabkehadiran_insertAsync(int nis, string namaSiswa, string presensi, object userState) {
            if ((this.tabkehadiran_insertOperationCompleted == null)) {
                this.tabkehadiran_insertOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontabkehadiran_insertOperationCompleted);
            }
            this.InvokeAsync("tabkehadiran_insert", new object[] {
                        nis,
                        namaSiswa,
                        presensi}, this.tabkehadiran_insertOperationCompleted, userState);
        }
        
        private void Ontabkehadiran_insertOperationCompleted(object arg) {
            if ((this.tabkehadiran_insertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tabkehadiran_insertCompleted(this, new tabkehadiran_insertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/tabkehadiran_update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string tabkehadiran_update(int nis, string namaSiswa, string presensi) {
            object[] results = this.Invoke("tabkehadiran_update", new object[] {
                        nis,
                        namaSiswa,
                        presensi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tabkehadiran_updateAsync(int nis, string namaSiswa, string presensi) {
            this.tabkehadiran_updateAsync(nis, namaSiswa, presensi, null);
        }
        
        /// <remarks/>
        public void tabkehadiran_updateAsync(int nis, string namaSiswa, string presensi, object userState) {
            if ((this.tabkehadiran_updateOperationCompleted == null)) {
                this.tabkehadiran_updateOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontabkehadiran_updateOperationCompleted);
            }
            this.InvokeAsync("tabkehadiran_update", new object[] {
                        nis,
                        namaSiswa,
                        presensi}, this.tabkehadiran_updateOperationCompleted, userState);
        }
        
        private void Ontabkehadiran_updateOperationCompleted(object arg) {
            if ((this.tabkehadiran_updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tabkehadiran_updateCompleted(this, new tabkehadiran_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/tabkehadiran_delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string tabkehadiran_delete(int nis) {
            object[] results = this.Invoke("tabkehadiran_delete", new object[] {
                        nis});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tabkehadiran_deleteAsync(int nis) {
            this.tabkehadiran_deleteAsync(nis, null);
        }
        
        /// <remarks/>
        public void tabkehadiran_deleteAsync(int nis, object userState) {
            if ((this.tabkehadiran_deleteOperationCompleted == null)) {
                this.tabkehadiran_deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontabkehadiran_deleteOperationCompleted);
            }
            this.InvokeAsync("tabkehadiran_delete", new object[] {
                        nis}, this.tabkehadiran_deleteOperationCompleted, userState);
        }
        
        private void Ontabkehadiran_deleteOperationCompleted(object arg) {
            if ((this.tabkehadiran_deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tabkehadiran_deleteCompleted(this, new tabkehadiran_deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/tabsiswa_insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string tabsiswa_insert(int id, string namaSiswa, System.DateTime tanggal, string jenisKelamin, string nomorHp, string email) {
            object[] results = this.Invoke("tabsiswa_insert", new object[] {
                        id,
                        namaSiswa,
                        tanggal,
                        jenisKelamin,
                        nomorHp,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tabsiswa_insertAsync(int id, string namaSiswa, System.DateTime tanggal, string jenisKelamin, string nomorHp, string email) {
            this.tabsiswa_insertAsync(id, namaSiswa, tanggal, jenisKelamin, nomorHp, email, null);
        }
        
        /// <remarks/>
        public void tabsiswa_insertAsync(int id, string namaSiswa, System.DateTime tanggal, string jenisKelamin, string nomorHp, string email, object userState) {
            if ((this.tabsiswa_insertOperationCompleted == null)) {
                this.tabsiswa_insertOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontabsiswa_insertOperationCompleted);
            }
            this.InvokeAsync("tabsiswa_insert", new object[] {
                        id,
                        namaSiswa,
                        tanggal,
                        jenisKelamin,
                        nomorHp,
                        email}, this.tabsiswa_insertOperationCompleted, userState);
        }
        
        private void Ontabsiswa_insertOperationCompleted(object arg) {
            if ((this.tabsiswa_insertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tabsiswa_insertCompleted(this, new tabsiswa_insertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/tabsiswa_update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string tabsiswa_update(int id, string namaSiswa, System.DateTime tanggal, string jenisKelamin, string nomorHp, string email) {
            object[] results = this.Invoke("tabsiswa_update", new object[] {
                        id,
                        namaSiswa,
                        tanggal,
                        jenisKelamin,
                        nomorHp,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tabsiswa_updateAsync(int id, string namaSiswa, System.DateTime tanggal, string jenisKelamin, string nomorHp, string email) {
            this.tabsiswa_updateAsync(id, namaSiswa, tanggal, jenisKelamin, nomorHp, email, null);
        }
        
        /// <remarks/>
        public void tabsiswa_updateAsync(int id, string namaSiswa, System.DateTime tanggal, string jenisKelamin, string nomorHp, string email, object userState) {
            if ((this.tabsiswa_updateOperationCompleted == null)) {
                this.tabsiswa_updateOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontabsiswa_updateOperationCompleted);
            }
            this.InvokeAsync("tabsiswa_update", new object[] {
                        id,
                        namaSiswa,
                        tanggal,
                        jenisKelamin,
                        nomorHp,
                        email}, this.tabsiswa_updateOperationCompleted, userState);
        }
        
        private void Ontabsiswa_updateOperationCompleted(object arg) {
            if ((this.tabsiswa_updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tabsiswa_updateCompleted(this, new tabsiswa_updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/tabsiswa_delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string tabsiswa_delete(int id) {
            object[] results = this.Invoke("tabsiswa_delete", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tabsiswa_deleteAsync(int id) {
            this.tabsiswa_deleteAsync(id, null);
        }
        
        /// <remarks/>
        public void tabsiswa_deleteAsync(int id, object userState) {
            if ((this.tabsiswa_deleteOperationCompleted == null)) {
                this.tabsiswa_deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontabsiswa_deleteOperationCompleted);
            }
            this.InvokeAsync("tabsiswa_delete", new object[] {
                        id}, this.tabsiswa_deleteOperationCompleted, userState);
        }
        
        private void Ontabsiswa_deleteOperationCompleted(object arg) {
            if ((this.tabsiswa_deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tabsiswa_deleteCompleted(this, new tabsiswa_deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void attentab_insertCompletedEventHandler(object sender, attentab_insertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class attentab_insertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal attentab_insertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void attentab_updateCompletedEventHandler(object sender, attentab_updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class attentab_updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal attentab_updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void attentab_deleteCompletedEventHandler(object sender, attentab_deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class attentab_deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal attentab_deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void entab_insertCompletedEventHandler(object sender, entab_insertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class entab_insertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal entab_insertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void entab_updateCompletedEventHandler(object sender, entab_updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class entab_updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal entab_updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void entab_deleteCompletedEventHandler(object sender, entab_deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class entab_deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal entab_deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Sectiontab_insertCompletedEventHandler(object sender, Sectiontab_insertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sectiontab_insertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Sectiontab_insertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Sectiontab_updateCompletedEventHandler(object sender, Sectiontab_updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sectiontab_updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Sectiontab_updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Sectiontab_deleteCompletedEventHandler(object sender, Sectiontab_deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sectiontab_deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Sectiontab_deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tabdaftar_insertCompletedEventHandler(object sender, tabdaftar_insertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tabdaftar_insertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tabdaftar_insertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tabdaftar_updateCompletedEventHandler(object sender, tabdaftar_updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tabdaftar_updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tabdaftar_updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tabdaftar_deleteCompletedEventHandler(object sender, tabdaftar_deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tabdaftar_deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tabdaftar_deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tabguru_insertCompletedEventHandler(object sender, tabguru_insertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tabguru_insertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tabguru_insertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tabguru_updateCompletedEventHandler(object sender, tabguru_updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tabguru_updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tabguru_updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tabguru_deleteCompletedEventHandler(object sender, tabguru_deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tabguru_deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tabguru_deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tabkehadiran_insertCompletedEventHandler(object sender, tabkehadiran_insertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tabkehadiran_insertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tabkehadiran_insertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tabkehadiran_updateCompletedEventHandler(object sender, tabkehadiran_updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tabkehadiran_updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tabkehadiran_updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tabkehadiran_deleteCompletedEventHandler(object sender, tabkehadiran_deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tabkehadiran_deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tabkehadiran_deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tabsiswa_insertCompletedEventHandler(object sender, tabsiswa_insertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tabsiswa_insertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tabsiswa_insertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tabsiswa_updateCompletedEventHandler(object sender, tabsiswa_updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tabsiswa_updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tabsiswa_updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void tabsiswa_deleteCompletedEventHandler(object sender, tabsiswa_deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tabsiswa_deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tabsiswa_deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591